name: Deploy to Azure App Service

on:
  push:
    branches:
      - master
  release:
    types:
      - published

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build with dotnet
      run: dotnet build api/Quizine.sln --configuration Release

    - name: dotnet publish
      run: dotnet publish api/Quizine.sln -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: quizine
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5950DC6FD8F9443A8ACD99DED598692F }}
        package: ${{env.DOTNET_ROOT}}/myapp

