name: Deploy to Firebase Hosting
'on':
  push:
    branches:
      - master
      
env: 
  REACT_APP_QUIZINE_API_KEY: ${{ secrets.REACT_APP_QUIZINE_API_KEY }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
        working-directory: ./client
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: ./client
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_QUIZINE_APP }}'
          channelId: live
          projectId: quizine-app
